### ISSUE TITLE
Mixed licensing

### ISSUE THREAD

**Issue by PhilHannent** [disusered/cordova-safe#3]
Hi,

Looking over the src folder I noticed that the code for Android and iOS is licensed as GPL2, however the LICENSE file in the root is MIT. Is that intentional?

Regards
Phil

**Comment by disusered** [comment]
No, it's not, thanks for pointing that out. At an early stage I considered GPL but stuck with MIT and didn't update the license headers. I'll have this updated in no time, thanks!
