### ISSUE TITLE
404 Not Found: cordova-safe

### ISSUE THREAD

**Issue by mhilcher** [disusered/cordova-safe#4]
Hi,

I added the plugin to my cordova project and it is shown in the plugin directory.
But I get this error when trying to compile the project.

When I type "cordova plugins" in the project directory I get the following output:
```
cordova-safe 1.0.6 "Safe"
org.apache.cordova.camera 0.3.6 "Camera"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transfer"
org.apache.cordova.geolocation 0.3.12 "Geolocation"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
```

Where is the error?

Thx, Martin

**Comment by disusered** [comment]
Hi, I received a similar report due to RNCryptor. I've been busy but I plan on fixing it tomorrow, thanks for the report!

**Comment by bgrayburn** [comment]
any chance this would be fixed soon? thanks for the library! much needed

**Comment by disusered** [comment]
That was the loooooooooooooongest tomorrow! Yes, I am working on it now, I was between projects and very backed up! Glad to be able to contribute again, I will update this issue when I have something to push.

**Comment by bgrayburn** [comment]
Thank you Carlos, no worries

**Comment by disusered** [comment]
I am looking at this and made some progress, tomorrow I will continue and hopefully release a fix!

**Comment by bgrayburn** [comment]
Thanks!

**Comment by disusered** [comment]
No problem! https://travis-ci.org/disusered/cordova-safe has a log of the plugin getting automatically installed and setup in an emulator. It doesn't run the test suite, but I did manually and fixed behavior on Android and iOS. Hopefully this addresses the issue you encountered!
