### ISSUE TITLE
error code 1 on encrypt

### ISSUE THREAD

**Issue by bgrayburn** [disusered/cordova-safe#7]
So i've got the lib up and in the dom in android, but I'm consistently getting an error code 1 when running encrypt.

here's my code:

    Meteor.enc.safe.encrypt = (fn)->
      console.log "about to encrypt: "+fn
      success = (encryptedFile) ->
        console.log 'Encrypted file: ' + encryptedFile
        return
      error = (c)->
        console.log 'Error with encryption operation, code: ' + c.toString()
        return
    
      Meteor.enc.safe.safe.encrypt fn, "someKey", success, error

I'm recording a video using the cordova-plugin-media-capture plugin then using the cordova-plugin-file plugin to resolve the fileEntry object. From that I've tried calling the above with:

  -the fileEntry.nativeURL property (ex. "file:///storage/emulated/0/DCIM/Camera/VID_20150806_122744.3gp")
  -the fileEntry.fullPath property (ex. "/DCIM/Camera/VID_20150806_122744.3gp")
  -the fileEntry.toInternalURL() path (ex. "cdvfile://localhost/persistent/DCIM/Camera/VID_20150806_123214.3gp")

didn't really expect the last one to work but figured I'd try. All of these return an error code 1. Any idea what might be going on? I expected the nativeURL to be the right thing to pass, but no luck.

**Comment by disusered** [comment]
Looks like permissions issues with the Java plugin. I made some assumptions about storage that don't always hold up. I'm reading up docs and am working on a solution now!

**Comment by bgrayburn** [comment]
you're awesome, thank you!

**Comment by disusered** [comment]
I wrote some manual tests to replicate the issue, I made some progress and will continue tomorrow. Thanks again for the feedback!

**Comment by bgrayburn** [comment]
thanks, let me know if I can provide any assistance

**Comment by disusered** [comment]
I just pushed an update to address issues with finding files, the Java code is now using a core Cordova method to normalize paths. In a future update I will try to detect file objects directly as well. Hope this addresses your issue, if not let me know and we'll try something else :+1:
