### ISSUE TITLE
Success callbacks not getting fired for Android with Cordova 5.4.1 and 6.0.0

### ISSUE THREAD

**Issue by Chuxel** [disusered/cordova-safe#9]
While encrypt and decrypt operations appear to fully succeed, the success callbacks do not appear to be getting fired when using recent versions of Cordova (repro'd on 5.4.1 and 6.0.0) when using example code in readme.

**Comment by pallaviMN** [comment]
@Chuxel , did u solve this issue? or used any other cordova plugin for encrypt it

**Comment by Chuxel** [comment]
Given the lack of response, the Intel App Security Cordova plugin looks like a better option. https://software.intel.com/en-us/app-security-api
